**Importing Libraries and Packages**

In [4]:
import numpy as np

In [5]:
np.set_printoptions(suppress = True, linewidth = 100 , precision = 2) 

**‌Importing Data**

In [6]:
raw_data = np.genfromtxt('loan-data.csv', delimiter = ';', encoding = 'latin-1', skip_header = 1)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

**‌Checking for incomplete Data**

In [7]:
np.isnan(raw_data).sum()

88005

In [8]:
temp_fill = np.nanmax(raw_data)+1
temp_mean = np.nanmean(raw_data, axis = 0)

/var/folders/ks/jkjfh7l92w55vt0hc51b8spr0000gn/T/ipykernel_1348/314499198.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data, axis = 0)


In [9]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [10]:
temp_stats = np.array([np.nanmin(raw_data, axis = 0),temp_mean,np.nanmax(raw_data, axis = 0)])

/var/folders/ks/jkjfh7l92w55vt0hc51b8spr0000gn/T/ipykernel_1348/1250670646.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data, axis = 0),temp_mean,np.nanmax(raw_data, axis = 0)])


In [11]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

**‌Splitting The Dataset**

In [12]:
col_str = np.argwhere(np.isnan(temp_mean)).squeeze()
col_str

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [13]:
col_num = np.argwhere(np.isnan(temp_mean)==False).squeeze()
col_num

array([ 0,  2,  4,  6,  7, 13])

**‌Re-importing The Dataset**

In [14]:
loan_data_str = np.genfromtxt('loan-data.csv', delimiter = ';' , autostrip=True, skip_header = 1, usecols = col_str, dtype = str, encoding = 'Latin-1')
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [15]:
loan_data_num = np.genfromtxt('loan-data.csv', delimiter = ';' , autostrip=True, skip_header = 1, usecols = col_num, dtype = np.number, encoding = 'Latin-1', filling_values = temp_fill)
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

**‌Headers Name**

In [16]:
w_header = np.genfromtxt('loan-data.csv', delimiter = ';' , autostrip=True, skip_footer = raw_data.shape[0], dtype = str, encoding = 'Latin-1')
w_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [17]:
header_str , header_num = w_header[col_str], w_header[col_num]

**Manipulating col_str**
‌Issue Date

In [18]:
loan_data_str[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [19]:
loan_data_str[:,0] = np.chararray.strip(loan_data_str[:,0],"-15")

In [20]:
np.unique(loan_data_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [21]:
month = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [22]:
for i in range(13):
    loan_data_str[:,0] = np.where(loan_data_str[:,0] == month[i], i, loan_data_str[:,0])

In [23]:
np.unique(loan_data_str[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

**Manipulating col_str**
‌Loan Status

In [24]:
np.unique(loan_data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [25]:
np.unique(loan_data_str[:,1]).size

9

In [26]:
bad_status = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [27]:
loan_data_str[:,1] = np.where(np.isin(loan_data_str[:,1],bad_status),0,1)

In [28]:
np.unique(loan_data_str[:,1])

array(['0', '1'], dtype='<U69')

**Manipulating col_str**
Term

In [29]:
loan_data_str[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [30]:
np.unique(loan_data_str[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [31]:
loan_data_str[:,2] = np.chararray.strip(loan_data_str[:,2]," months")

In [32]:
np.unique(loan_data_str[:,2])

array(['', '36', '60'], dtype='<U69')

In [33]:
header_str[2] = "term_month"

In [34]:
loan_data_str[:,2] = np.where(loan_data_str[:,2] == '' , '60',loan_data_str[:,2])

In [35]:
np.unique(loan_data_str[:,2])

array(['36', '60'], dtype='<U69')

**Manipulating col_str**
grade , sub_grade

In [36]:
header_str

array(['issue_d', 'loan_status', 'term_month', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [37]:
np.unique(loan_data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [38]:
np.unique(loan_data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [39]:
for i in np.unique(loan_data_str[:,3])[1:]:
    loan_data_str[:,4] = np.where((loan_data_str[:,4] == '') & (loan_data_str[:,3] == i),i+'5',loan_data_str[:,4])

In [40]:
np.unique(loan_data_str[:,4],return_counts= True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [41]:
loan_data_str[:,4] = np.where(loan_data_str[:,4] == '', 'H1',loan_data_str[:,4])

In [42]:
np.unique(loan_data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Removing grade

In [43]:
loan_data_str = np.delete(loan_data_str,3,axis = 1)

In [44]:
loan_data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [45]:
header_str = np.delete(header_str,3)

In [46]:
header_str

array(['issue_d', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [47]:
loan_data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

Filling Sub-grade

In [48]:
np.unique(loan_data_str[:,3]).size

36

In [49]:
np.unique(loan_data_str[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [50]:
keys = list(np.unique(loan_data_str[:,3]))

In [51]:
values = list(range(1,np.unique(loan_data_str[:,3]).shape[0]+1))

In [52]:
dict_sub_grade = dict(zip(keys,values))

In [53]:
dict_sub_grade['A1']

1

In [54]:
for i in np.unique(loan_data_str[:,3]):
    loan_data_str[:,3] = np.where(loan_data_str[:,3] == i,dict_sub_grade[i],loan_data_str[:,3]) 

In [55]:
np.unique(loan_data_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

**Manipulating col_str**
verification status

In [56]:
header_str

array(['issue_d', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [57]:
loan_data_str[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [58]:
np.unique(loan_data_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [59]:
loan_data_str[:,4] = np.where((loan_data_str[:,4] == '') | (loan_data_str[:,4] == 'Not Verified'),0,1)

In [60]:
np.unique(loan_data_str[:,4])

array(['0', '1'], dtype='<U69')

**Manipulating col_str**
URL

In [61]:
loan_data_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [62]:
loan_data_str[:,5] = np.chararray.strip(loan_data_str[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [63]:
loan_data_str[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [64]:
w_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [65]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [66]:
header_num[0]

'id'

In [67]:
type(loan_data_num[:,0])

numpy.ndarray

In [68]:
np.array_equal(loan_data_num[:,0],loan_data_str[:,5].astype(dtype = np.int32))

True

In [69]:
loan_data_str = np.delete(loan_data_str,5,axis = 1)

In [70]:
header_str = np.delete(header_str, 5)

In [71]:
loan_data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [72]:
loan_data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [73]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**Manipulating col_str**
State Address

In [74]:
header_str

array(['issue_d', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [75]:
loan_data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [76]:
np.unique(loan_data_str[:,5]).size

50

In [77]:
np.unique(loan_data_str[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27]))

In [78]:
states_name , states_count = np.unique(loan_data_str[:,5],return_counts=True)

In [79]:
states_count_sort = np.argsort(-states_count)

In [80]:
states_name[states_count_sort],states_count[states_count_sort]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [81]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [82]:
loan_data_str[:,5] = np.where(loan_data_str[:,5]=='',0,loan_data_str[:,5])

In [83]:
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5],states_west),1,loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5],states_south),2,loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5],states_midwest),3,loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5],states_east),4,loan_data_str[:,5])

In [84]:
np.unique(loan_data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

**Manipulating col_str**
Converting to Number

In [85]:
loan_data_str

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [86]:
loan_data_str = loan_data_str.astype(int)

In [87]:
loan_data_str

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

**Checkpoint String**

In [88]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [89]:
checkpoint_str = checkpoint('Checkpoint-Strings',header_str,loan_data_str)

In [90]:
checkpoint_str['header']

array(['issue_d', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [91]:
checkpoint_str['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [92]:
np.array_equal(checkpoint_str['data'],loan_data_str)

True

**Manipulating col_num**

In [93]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [94]:
np.isnan(loan_data_num).sum()

0

In [95]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**Manipulating col_num**
ID

In [96]:
temp_fill

68616520.0

In [97]:
np.isin(loan_data_num[:,0],temp_fill).sum()

0

In [98]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [99]:
temp_stats[:,col_num]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

**Manipulating col_num**
Founded Amnt

In [100]:
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [101]:
loan_data_num[:,2] = np.where(loan_data_num[:,2] == temp_fill,temp_stats[0,col_num[2]],loan_data_num[:,2])

In [102]:
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

**Manipulating col_num**
Loan Amnt,int Rate, installment, total payment

In [103]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [104]:
for i in [1,3,4,5]:
    loan_data_num[:,i] = np.where(loan_data_num[:,i] == temp_fill,temp_stats[2,col_num[i]],loan_data_num[:,i])

In [105]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

**Currency Exchange**
The Exchange rate

In [106]:
EUR_USD = np.genfromtxt("EUR-USD.csv" , delimiter = ',' , autostrip = True, skip_header = 1, usecols = 3)

In [107]:
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [108]:
loan_data_str[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [109]:
exchange_rate = loan_data_str[:,0]

In [110]:
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [111]:
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,EUR_USD[i-1],exchange_rate)

exchange_rate = np.where(exchange_rate == 0,np.mean(EUR_USD),exchange_rate)


In [112]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [113]:
exchange_rate.shape

(10000,)

In [114]:
loan_data_num.shape

(10000, 6)

In [115]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [116]:
loan_data_num = np.hstack((loan_data_num,exchange_rate))

In [117]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [118]:
header_num = np.concatenate((header_num,np.array(['exchange_rate'])))

In [119]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

**Currency Exchange**
USD to EUR

In [120]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [121]:
col_dollar = np.array([1,2,4,5])

In [122]:
loan_data_num[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [123]:
for i in col_dollar:
    loan_data_num = np.hstack((loan_data_num,np.reshape(loan_data_num[:,i]/loan_data_num[:,6],(10000,1))))

In [124]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

**Expanding Header**

In [140]:
header_num_additional = np.array([col_num + '_EUR' for col_num in header_num[col_dollar]])

In [127]:
header_num_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [128]:
header_num = np.concatenate((header_num,header_num_additional))

In [129]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [130]:
header_num[col_dollar] = np.array([col_num + '_USD' for col_num in header_num[col_dollar]])

In [132]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [133]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [135]:
header_num = header_num[column_index_order]

In [136]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [137]:
loan_data_num = loan_data_num[:,column_index_order]

In [139]:
loan_data_num

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

**int Rate**

In [141]:
loan_data_num[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [142]:
loan_data_num[:,5] = loan_data_num[:,5]/100

In [143]:
loan_data_num[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

**Checkpoint Numeric**

In [144]:
checkpoint_num = checkpoint('Checkpoint-Numeric',header_num,loan_data_num)

In [145]:
checkpoint_num['header'],checkpoint_num['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

**Complete Dataset**

In [146]:
checkpoint_num['data'].shape

(10000, 11)

In [147]:
checkpoint_str['data'].shape

(10000, 6)

In [148]:
loan_data = np.hstack((checkpoint_num['data'],checkpoint_str['data']))

In [149]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [151]:
np.isnan(loan_data).sum()

0

In [152]:
header_full = np.concatenate((checkpoint_num['header'],checkpoint_str['header']))

In [153]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_d', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

**Sorting Dataset**

In [158]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [159]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [160]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

**Saving Dataset**

In [162]:
loan_data = np.vstack((header_full,loan_data))

In [163]:
np.savetxt("loan-data-preprocessed.csv",loan_data, delimiter = ',', fmt = '%s')